# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PartyHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PartyHub
  pod 'PinLayout'
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'FirebaseAuth'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'Kingfisher'
  pod 'NVActivityIndicatorView', '~> 4.8.0'
  pod 'YandexMapsMobile', '4.1.0-lite'

end
